<?xml version="1.0" encoding="utf-8"?><Database Name="HolidayPlanner" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MacServer;Initial Catalog=HolidayPlanner;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HolidayPlannerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="CountryId" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Country_State" Member="States" ThisKey="CountryId" OtherKey="CountryId" Type="State" />
    </Type>
  </Table>
  <Table Name="dbo.State" Member="States">
    <Type Name="State">
      <Column Name="StateId" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="State_City" Member="Cities" ThisKey="StateId" OtherKey="StateId" Type="City" />
      <Association Name="Country_State" Member="Country" ThisKey="CountryId" OtherKey="CountryId" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.City" Member="Cities">
    <Type Name="City">
      <Column Name="CityId" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StateId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="State_City" Member="State" ThisKey="StateId" OtherKey="StateId" Type="State" IsForeignKey="true" />
    </Type>
  </Table>
</Database>